# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/realme/RMX3521/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),RMX3521)

$(call add-radio-file-sha1-checked,radio/abl.img,12e0749c8e07e06c29e09702c406e424142477e6)
$(call add-radio-file-sha1-checked,radio/bluetooth.img,e683e76279713ad47e3df8d3e73f2cd66f4952f5)
$(call add-radio-file-sha1-checked,radio/devcfg.img,52d8e464e1bf2f6558f43463a90a712faed8fc91)
$(call add-radio-file-sha1-checked,radio/dsp.img,898208e38ef9320016577312b46fe14a0ea6b05b)
$(call add-radio-file-sha1-checked,radio/featenabler.img,7adaa105931cc765ecc7d04fc25495e10f4670e4)
$(call add-radio-file-sha1-checked,radio/hyp.img,251e314dc2dc922b13b3b4f57c1a227cabdaeda6)
$(call add-radio-file-sha1-checked,radio/imagefv.img,c078232cf971c4ada0d64c470d1f46c3e4cebad6)
$(call add-radio-file-sha1-checked,radio/keymaster.img,8de1ffa726b1cfc5b2efd304db08e079bb0f2fef)
$(call add-radio-file-sha1-checked,radio/modem.img,cc65f8fd7a25f26f9c3876fc5cc1c49fb4995b39)
$(call add-radio-file-sha1-checked,radio/multiimgoem.img,59c18ffa3da1b88fee83634d024af43187716cf8)
$(call add-radio-file-sha1-checked,radio/oplus_sec.img,94df681967b295167521c040187827bb042758a4)
$(call add-radio-file-sha1-checked,radio/oplusstanvbk.img,30b4dc6624fa94a61244bb17ee8c52d0fe592b17)
$(call add-radio-file-sha1-checked,radio/qupfw.img,e5a80e7686f964989bbbde114a9ced38ba138f3f)
$(call add-radio-file-sha1-checked,radio/rpm.img,dfc86d3353ce424556c1ddf9c2ff3a6452aa6355)
$(call add-radio-file-sha1-checked,radio/splash.img,8399d0eb69bbe8c7471befae3b95eb30c11a2d36)
$(call add-radio-file-sha1-checked,radio/tz.img,2b9c0a01cb07962f89c42cfd34d8aacb293ed679)
$(call add-radio-file-sha1-checked,radio/uefisecapp.img,9c8b4f97d91903dcfc28d68c8b2e0ef73e1a890d)
$(call add-radio-file-sha1-checked,radio/xbl_config.img,f297c47efebdab5d203020a1b32492b53dffd8b5)
$(call add-radio-file-sha1-checked,radio/xbl.img,453f70e49a2875de3b337ada8adca5e84133d3d1)

endif
