# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/realme/RMX3521/setup-makefiles.sh

# A.31 Firmwares
AB_OTA_PARTITIONS += \
    abl \
    bluetooth \
    devcfg \
    dsp \
    featenabler \
    hyp \
    imagefv \
    keymaster \
    modem \
    multiimgoem \
    oplus_sec \
    oplusstanvbk \
    qupfw \
    rpm \
    splash \
    tz \
    uefisecapp \
    xbl \
    xbl_config
